// Code generated by MockGen. DO NOT EDIT.
// Source: app/ports/host/reader.go
//
// Generated by this command:
//
//	mockgen -destination mocks/ports/host/reader.go -source=app/ports/host/reader.go HostReader
//

// Package mock_host is a generated GoMock package.
package mock_host

import (
	reflect "reflect"

	host "github.com/PaoGRodrigues/tfi-backend/app/domain/host"
	gomock "go.uber.org/mock/gomock"
)

// MockHostReader is a mock of HostReader interface.
type MockHostReader struct {
	ctrl     *gomock.Controller
	recorder *MockHostReaderMockRecorder
	isgomock struct{}
}

// MockHostReaderMockRecorder is the mock recorder for MockHostReader.
type MockHostReaderMockRecorder struct {
	mock *MockHostReader
}

// NewMockHostReader creates a new mock instance.
func NewMockHostReader(ctrl *gomock.Controller) *MockHostReader {
	mock := &MockHostReader{ctrl: ctrl}
	mock.recorder = &MockHostReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostReader) EXPECT() *MockHostReaderMockRecorder {
	return m.recorder
}

// GetAllHosts mocks base method.
func (m *MockHostReader) GetAllHosts() ([]host.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHosts")
	ret0, _ := ret[0].([]host.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHosts indicates an expected call of GetAllHosts.
func (mr *MockHostReaderMockRecorder) GetAllHosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHosts", reflect.TypeOf((*MockHostReader)(nil).GetAllHosts))
}
